/**
 * Generates src/generated/*: package metadata, the embedded font (base64) and
 * the prebuilt browser viewer bundle as a string module. Keeping these as TS
 * modules means `storyink/core` needs no runtime file reads.
 */
import fs from "node:fs"
import path from "node:path"

const root = path.resolve(import.meta.dir, "..")
const out = path.join(root, "src/generated")
fs.mkdirSync(out, { recursive: true })

const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"))
const write = (name: string, body: string) => {
  const file = path.join(out, name)
  const text = `// Generated by scripts/gen.ts. Do not edit.\n${body}`
  if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== text) fs.writeFileSync(file, text)
}

write("meta.ts", `export const VERSION = ${JSON.stringify(pkg.version)}\n`)

// Placeholder so the viewer (which imports core modules) can resolve before the real bundle exists.
if (!fs.existsSync(path.join(out, "viewer.ts"))) write("viewer.ts", `export const VIEWER_JS = ""\n`)

const font = (w: number) => fs.readFileSync(path.join(root, `fonts/CommitMono-${w}.woff2`)).toString("base64")
write(
  "font.ts",
  `/** Commit Mono v1.143 (SIL OFL 1.1, see fonts/OFL.txt), woff2, base64. */\n` +
    `export const COMMIT_MONO_400 = ${JSON.stringify(font(400))}\n` +
    `export const COMMIT_MONO_700 = ${JSON.stringify(font(700))}\n`,
)

const version = (name: string) => JSON.parse(fs.readFileSync(path.join(root, "node_modules", name, "package.json"), "utf8")).version
const banner = `/*! storyink viewer ${pkg.version} | MIT
 * Bundles:
 *  react ${version("react")}, react-dom ${version("react-dom")}, scheduler ${version("scheduler")}
 *    MIT License. Copyright (c) Meta Platforms, Inc. and affiliates.
 *  motion ${version("motion")} (framer-motion ${version("framer-motion")}, motion-dom ${version("motion-dom")}, motion-utils ${version("motion-utils")})
 *    MIT License. Copyright (c) 2024 Motion B.V.; Copyright (c) 2018 Framer B.V.
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 *  associated documentation files (the "Software"), to deal in the Software without restriction,
 *  including without limitation the rights to use, copy, modify, merge, publish, distribute,
 *  sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions: The above copyright notice and this
 *  permission notice shall be included in all copies or substantial portions of the Software.
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.
 */
`

const result = await Bun.build({
  entrypoints: [path.join(root, "src/viewer/main.tsx")],
  target: "browser",
  format: "iife",
  minify: true,
  define: { "process.env.NODE_ENV": '"production"' },
})
if (!result.success) {
  for (const l of result.logs) console.error(l)
  process.exit(1)
}
const js = banner + (await result.outputs[0].text())
write("viewer.ts", `export const VIEWER_JS = ${JSON.stringify(js)}\n`)
console.log(`gen: viewer ${(js.length / 1024).toFixed(1)} KiB, font ${((font(400).length + font(700).length) / 1024).toFixed(1)} KiB base64`)
